<?xml version="1.0"?>
<robot name = "my_ros_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find my_ros_robot_description)/urdf/chassis.xacro"/>
    <xacro:include filename="$(find my_ros_robot_description)/urdf/properties.xacro"/>
    <xacro:include filename="$(find my_ros_robot_description)/urdf/wheel.xacro"/>

    <xacro:chassis/>
    <xacro:wheel name="left" translation="0 ${WHEEL_SEPARATION / 2} 0" rotation="0 0 0" parent="base_link"/>
    <xacro:wheel name="right" translation="0 ${-WHEEL_SEPARATION / 2} 0" rotation="0 0 0" parent="base_link"/>

</robot>